name: Docker CD

on:
  push:
    branches:
      - master
      - develop
      - release/*
    tags:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Push
        uses: warchant/Publish-Docker-Github-Action@3
        with:
          name: veriblock/vbtc-explorer
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          tag_names: true
